---

- hosts:  webservers
  become: yes

  tasks:

    - name: Install nginx servers and PHP packages
      apt:
        update_cache: yes
        name: ['nginx', 'php', 'php-fpm']
        state:  present

    - name: Move default template to servers
      copy:
        src:  ./default
        dest: /etc/nginx/sites-available/default

    - name: Restart the nginx servers
      service:
        name: nginx
        state:  restarted
    
    - name: Move index page to target servers
      copy:
        src:  ./index.php
        dest: /var/www/html/index.php

- hosts:  haproxy
  become: yes

  tasks:
    - name: Install haproxy on devhaproxy
      apt:
        update_cache: yes
        name: haproxy
        state:  present

    - name: Move haproxy template to load balancers
      template:
        src:  haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Restart the haproxy server
      service:
        name: haproxy
        state:  restarted

    - name: Testing the deployed application 
      command:  curl "{{hostvars.devhaproxy.ansible_default_ipv4.address}}"
      args:
        warn: no
      register: test

    - debug:
        msg:  "{{test.stdout}}"

    - name: Testing the deployed application 
      command:  curl "{{hostvars.devhaproxy.ansible_default_ipv4.address}}"
      args:
        warn: no
      register: test

    - debug:
        msg:  "{{test.stdout}}"

    - name: Testing the deployed application 
      command:  curl "{{hostvars.devhaproxy.ansible_default_ipv4.address}}"
      args:
        warn: no
      register: test

    - debug:
        msg:  "{{test.stdout}}"