---

- hosts:  webservers

  tasks:

    - name: Install nginx servers
      apt:
        update_cache: yes
        name: nginx
        state:  present

    - name: Move default template to servers
      copy:
        src:  ./default
        dest: /etc/nginx/sites-available/default

      
    